In [5]:
import numpy as np

In [ ]:
#Q.NO.1: Array Creation

In [ ]:
#Create a 1-dimensional array of integers from 1 to 10.

In [3]:
array_1d = np.arange(1, 11)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Create a 2-dimensional array with random float values of shape (3, 4).

In [7]:
array_2d = np.random.rand(3, 4)
array_2d

array([[0.19597403, 0.39602272, 0.10618824, 0.03507249],
       [0.00395988, 0.67581262, 0.46816151, 0.47816459],
       [0.72499671, 0.76349317, 0.82804047, 0.06144671]])

In [9]:
#Create a 3-dimensional array of zeros with shape (2, 3, 4).

In [11]:
array_3d = np.zeros((2, 3, 4))
array_3d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
# Q.No.2 Array Operations

In [15]:
#Given two 1-dimensional arrays, perform element-wise addition,subtraction, multiplication, and division.

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

c=a+b
c

array([ 6,  8, 10, 12])

In [19]:
d=a-b
d

array([-4, -4, -4, -4])

In [21]:
e=a*b
e

array([ 5, 12, 21, 32])

In [23]:
f=a/b
f

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [25]:
#Calculate the mean, median, and standard deviation of a given 1-dimensional array.

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6])

mean_value = np.mean(arr)
mean_value

3.5

In [29]:
median_value = np.median(arr)
median_value

3.5

In [31]:
std_value = np.std(arr)
std_value

1.707825127659933

In [33]:
#Reshape a 1-dimensional array into a 2-dimensional array of shape (3,4).

In [35]:
array_1d = np.arange(1, 13)  


reshaped_array = array_1d.reshape(3, 4)
reshaped_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
#Q.No.3 Array Indexing and Slicing

In [43]:
#Extract the first row and last column of a 2-dimensional array.

In [41]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

first_row = array_2d[0, :]
first_row

array([1, 2, 3])

In [45]:
last_column = array_2d[:, -1]
last_column

array([3, 6, 9])

In [47]:
#Reverse the order of elements in a 1-dimensional array.

In [49]:
array_1d = np.array([1, 2, 3, 4, 5])

reversed_array = array_1d[::-1]
reversed_array

array([5, 4, 3, 2, 1])

In [53]:
#Select elements from a 2-dimensional array that satisfy a specific condition (e.g., values greater than a certain threshold).

In [55]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

selected_elements = array_2d[array_2d > 5]
selected_elements

array([6, 7, 8, 9])

In [57]:
# Q.No.4 Array Broadcasting

In [63]:
#o Add a scalar value to each element of a 2-dimensional array.

In [61]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array_with_scalar = array_2d + 10
array_with_scalar

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [65]:
#Multiply a 1-dimensional array with a 2-dimensional array, leveraging NumPy's broadcasting rules.

In [67]:
array_1d = np.array([1, 2, 3])

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

result = array_2d * array_1d
result


array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [69]:
#Q.NO.5 LINEAR ALGEBRA

In [71]:
#Calculate the dot product of two 1-dimensional arrays.

In [73]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


dot_product = np.dot(a, b)
dot_product

32

In [75]:
#Compute the matrix multiplication of two 2-dimensional arrays.

In [77]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

matrix_product = np.matmul(A, B)  
matrix_product

array([[19, 22],
       [43, 50]])

In [79]:
#Find the inverse and determinant of a square matrix.

In [85]:
matrix = np.array([[1, 2], [3, 4]])

inverse_matrix = np.linalg.inv(matrix)
inverse_matrix




array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [87]:
determinant = np.linalg.det(matrix)
determinant

-2.0000000000000004